version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qaz098
      POSTGRES_DB: anime_sync
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5431:5431"

  backend:
    build: .
    environment:
      DB_USER: postgres
      DB_PASSWORD: qaz098
      DB_HOST: db
      DB_PORT: 5431
      DB_NAME: anime_sync
      JWT_SECRET: qazplm098123
    ports:
      - "5431:5431"
    depends_on:
      - db

volumes:
  db_data:

